server.port=8090

spring.application.name=tingeso

server.error.include-message=always
server.error.include-binding-errors=always
spring.jpa.hibernate.ddl-auto=update

spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:5432/tingeso
spring.datasource.username=postgres
spring.datasource.password=link5321
spring.datasource.driver-class-name=org.postgresql.Driver

spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:9090/realms/TravelAgency
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://host.docker.internal:9090/realms/TravelAgency/protocol/openid-connect/certs
keycloak.client-id=spring-boot-backend
keycloak.client-secret=5sAgpyCRJzqjDSguWJbsfmtEtP3BfYsH

# Business Rule: Group Discount
booking.discount.group.threshold=4
booking.discount.group.percentage=15
# Business Rule: Frequent Customer
booking.discount.frequent.threshold=3
booking.discount.frequent.percentage=10
# Business Rule: Multiple Packages Discount
booking.discount.multiple.days-limit=30
booking.discount.multiple.percentage=7
# Business Rule: Discount Limits
booking.discount.max-total-percentage=30
# Business Rule: Limited Time Promotion
booking.discount.promo.start-date=2026-05-01T00:00:00
booking.discount.promo.end-date=2026-05-31T23:59:59
booking.discount.promo.percentage=10