spring.application.name=tingeso

server.error.include-message=always
server.error.include-binding-errors=always
spring.jpa.hibernate.ddl-auto=update

spring.datasource.url=jdbc:postgresql://localhost:5432/tingeso
spring.datasource.username=postgres
spring.datasource.password=link5321
spring.datasource.driver-class-name=org.postgresql.Driver

spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:9090/realms/TravelAgency
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://localhost:9090/realms/TravelAgency/protocol/openid-connect/certs
keycloak.client-id=spring-boot-backend
keycloak.client-secret=5sAgpyCRJzqjDSguWJbsfmtEtP3BfYsH